name: 'aug_dbt_core'
version: '1.0.0'

profile: 'aug_dbt_core'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  aug_dbt_core:
    +materialized: view
    bronze:
      +database: BRONZE
      +schema: stg
      +materialized: table
    silver:
      +database: SILVER
      +schema: dbo
      +materialized: table
    gold:
      +database: GOLD
      +schema: dbo
      +materialized: view

seeds:
  aug_dbt_core:
